### ISSUE TITLE
WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.10007bac41_1

### ISSUE THREAD

**Issue by nirkons** [CoolKit-Technologies/ha-addon#21]
Every time I turn a switch on/off **outside of the addon web interface**, either through the HA panel or through Node-Red, this warning shows up in the HA log and this error shows up in the addon log

` {"error":0,"deviceid":"10007bac41","apikey":"xxxxxxx-xxxxx-xxxxxxx-xxxx-xxxxxxxxxx","sequence":"1627681417168"}
(node:21) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'outlet' of undefined
    at CloudMultiChannelSwitchController.<anonymous> (/workspace/controller/CloudMultiChannelSwitchController.js:108:47)
    at step (/workspace/controller/CloudMultiChannelSwitchController.js:46:23)
    at Object.next (/workspace/controller/CloudMultiChannelSwitchController.js:27:53)
    at /workspace/controller/CloudMultiChannelSwitchController.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/controller/CloudMultiChannelSwitchController.js:17:12)
    at CloudMultiChannelSwitchController.updateState (/workspace/controller/CloudMultiChannelSwitchController.js:101:12)
    at CloudMultiChannelSwitchController.<anonymous> (/workspace/controller/CloudMultiChannelSwitchController.js:89:30)
    at step (/workspace/controller/CloudMultiChannelSwitchController.js:46:23)
    at Object.next (/workspace/controller/CloudMultiChannelSwitchController.js:27:53)
(node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 32376)
receive CK-WS msg:   type--> message
receive CK-WS msg:
 pong
WS:接收到心跳信息 pong`

The switch does turn on/off though, the problem is that its filling up the logs and disk space.
This happens with every 4CH R3 device with latest ewelink firmware.

thanks

**Comment by ZJia1231** [comment]
We will look in to it.
Thx.

**Comment by nirkons** [comment]
Hi, any updates? still having this issue, filling up my logs all the time

**Comment by coolkit-tony** [comment]
Can you control this device from the addon web interface?

**Comment by nirkons** [comment]
> Can you control this device from the addon web interface?

Yes, controlling it works even with the error in the log

**Comment by niezw** [comment]
Please update to the latest version  v1.2.2
