### ISSUE TITLE
Strange supervisor logs related to add-on

### ISSUE THREAD

**Issue by n00bcodr** [CoolKit-Technologies/ha-addon#58]
I'm noticing these strange logs during the startup of the add-on. Anything I need to be concerned about?

```21-12-21 21:26:01 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_f4f71350_ewelink_smart_home_slug application
21-12-21 21:26:01 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on f4f71350/amd64-addon-ewelink_smart_home_slug with version 1.2.3
21-12-21 21:26:02 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-12-21 21:26:02 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-12-21 21:26:02 INFO (MainThread) [supervisor.api.proxy] WebSocket access from f4f71350_ewelink_smart_home_slug
21-12-21 21:26:02 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-12-21 21:26:31 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-264788' coro=<WebSocketWriter.ping() done, defined at /usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py:672> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 676, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 653, in _send_frame
    self._write(header + message)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

**Comment by niezw** [comment]
It looks like some system error reports.It is recommended to update HA to the latest.

If you have any more questions, please reopen this issues. Thank you for your reply.
